### ISSUE TITLE
Roxygen everything

### ISSUE THREAD

**Issue by courtiol** [courtiol/IsoriX_project#39]
It would be good to move all the help content into the R code using Roxygen.
I quite like the namespace as it is, but I don't know if we can keep it with Roxygen.

**Comment by f-rousset** [comment]
Assuming you have installed roxygen2, a tick box for Roxygen appears in Tools | Project options | Build Tools, and also a Configure button through which you you can deselect automatic NAMESPACE generation by Roxygen...
https://support.rstudio.com/hc/en-us/articles/200532317-Writing-Package-Documentation

**Comment by courtiol** [comment]
to convert everything, let's use: https://yihui.name/rd2roxygen/

**Comment by courtiol** [comment]
Marie, you must indicate all changes in the NEWS file

**Comment by courtiol** [comment]
We need to reoxygenize also the NAMESPACE. That is a bit of boring work... but it will make dependencies clearer within the code.

**Comment by courtiol** [comment]
done
